version: '3'

services: 
    site:
        build: .
        ports:
            - 8080:8080
        environment: 
            DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
        links:
            - db:postgres
        depends_on: 
            - db
    db:
        image: postgres
        restart: always
        ports: 
            - 5433:5432
        environment: 
            POSTGRES_PASSWORD: postgres
        