version: '3'

services: 
    site:
        build: .
        ports:
            - 8080:8080
        volumes: 
            - .:/site
        environment: 
            DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
        depends_on: 
            - db
    db:
        image: postgres
        ports: 
            - 5432:5432
        environment: 
            POSTGRES_PASSWORD: postgres
        